apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-nfs-pvc-busybox
  labels:
    name: nfs-demo
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
