  
# This ReplicationController mounts the nfs volume claim into /mnt and continuously
# overwrites /mnt/index.html with the time and hostname of the pod.
#### USE helm-deploynfs-busybox.yaml for using a Deployment instead. ####

apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server-busybox
spec:
  replicas: 2
  selector:
    name: nfs-busybox
  template:
    metadata:
      labels:
        name: nfs-busybox
    spec:
      containers:
      - image: busybox
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
          # name must match the volume name below
          - name: nfs-volume
            mountPath: "/mnt"
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: helm-nfs-pvc-busybox
