apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - account-db-pvc-clone.yaml
  - ledger-db-pvc-clone.yaml
  - balance-reader.yaml
  - config.yaml
  - contacts.yaml
  - frontend.yaml
  - jwt-secret.yaml
  - ledger-writer.yaml
  - loadgenerator.yaml
  - userservice.yaml
  - transaction-history.yaml
  - accounts-db.yaml
  - ledger-db.yaml