apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-provisioning-demo
  labels:
    name: nfs-demo
spec:
  storageClassName: ionir-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
